version: "3.9"
services: 
    webapp:
        build: ./
        ports:
            -   "8080:8080"
        depends_on:
            -   db
            -   broker
    broker:
        image: "rmohr/activemq"
        ports:
            -   "61616:61616"
            -   "8161:8161"
        environment:
            ACTIVEMQ_USER: "admin"
    db:
        image: "postgres:latest"
        ports:
            -   "5432:5432"
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "employeedb"
            PGPASSWORD: "password"
            PGUSER: "postgres"
            PGDATABASE: "employeedb"