version: "3.9"
services: 
    webapp:
        build: ./
        ports:
            -   "8080:8080"
    broker:
        image: "rmohr/activemq"
        ports:
            -   "61616:61616"
            -   "8161:8161"
    db:
        image: "postgres:latest"
        ports:
            -   "5432:5432"
        environment:
            POSTGRES_PASSWORD: "password"